# This is a basic workflow to help you get started with Actions
name: prh my action

on: push
jobs:
  prComment:
    runs-on: ubuntu-latest
    steps:
      - id: uppercase
        uses: itoaki/action-prh@v1.0.0
